[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#7cbec0"
green = "#b8bb26"
magenta = "#d773af"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.cursor]
cursor = "0xffe8c0"
text = "0x020221"

[colors.normal]
black = "#141414"
blue = "#458588"
cyan = "#5aa2a5"
green = "#98971a"
magenta = "#ad62b1"
red = "#cc231d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#141414"
foreground = "#dddddd"
