#!/bin/sh

PASS='Halmilive!"#4'

wlfreerdp '/u:\AzureAD\OW@axentia.se' \
    "/p:$PASS" \
    /v:OW-L1.local \
    /d:AzureAD \
    /cert:ignore \
    /sound \
    /gfx:avc420 \
    /microphone:sys:pulse \
    +aero \
    +compression \
    +clipboard \
    -sec-nla # \
    # /w:2560 \
    # /h:1440
