#!/bin/sh

sign=${1:0:1}
change=${1:1:-1}

if [ $sign == "+" ]; then
    echo -s sysfs/backlight/auto -A $change
    light -s sysfs/backlight/auto -A $change
else
    echo -s sysfs/backlight/auto -A $change
    light -s sysfs/backlight/auto -U $change
fi

brightness=$(light -s sysfs/backlight/auto -G)
notify-send --expire-time=3000 \
   --replace-id 106 \
   "Brightness ${brightness:0:-3}%" \
   -h int:value:$brightness \
   -h "string:wired-note:brightness"
#dunstify -a brightness \
#    -u low \
#    -i "brightnesssettings" \
#    -h int:value:$brightness "Brightness ${brightness:0:-3}%" \
#    -r 888
